@apiurl = http://localhost:5000/v1
@applicationToken = ba3d9e5a999111493f1cea52b7fe8e8fd6ea6fb4cadd8cf7b78e95e7f1c28347
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbmlzdHJhZG9yQGdtYWlsLmNvbSIsIm5vbWUiOiJhZG1pbmlzdHJhZG9yIiwiaWF0IjoxNjI4MTkzNTIyLCJleHAiOjE2MjgxOTcxMjJ9.rLXEdDQb36mFAEAWodvnuO7XRV0XhJi90PvnLxqwDLg
@secretHash = 85a598f40971a4f346c2fa2bf3aa38d71fc8908281c248fee160c0f25ca218bb

###
### Obter o Appliation Token
###

GET {{apiurl}}/applicationtoken HTTP/1.1
content-type: application/json
secret: {{secretHash}}

###
### Status da API
###

GET {{apiurl}}/status HTTP/1.1
content-type: application/json
application-token: {{applicationToken}}

###
### Login
###

POST {{apiurl}}/login HTTP/1.1
content-type: application/json
application-token: {{applicationToken}}

{
	"usr" : "administrador@gmail.com",
	"pwd" : "123456"
}

###
### Buscar Todos os Usuários
###

GET {{apiurl}}/usuario HTTP/1.1
content-type: application/json
application-token: {{applicationToken}}
token:{{userToken}}

###
### Buscar Usuário por ID
###

GET {{apiurl}}/usuario/1 HTTP/1.1
content-type: application/json
application-token: {{applicationToken}}
token:{{userToken}}